# Site
name: 'AI Supremacy SG'
title: 'AI Supremacy SG'
description: 'AI Supremacy SG is a Singapore based AI startup community.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: 'https://ai.supremacy.sg'
disqus: 'demowebsite'
email: 'info@supremacy.sg'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    alex:
      name:           Alex Tan
      site:           https://supremacy.sg
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Alex, the author of ai.supremacy.sg Featuring Singapore top notch AI startups."
      email:          info@sup.sg
      twitter:        https://discord.gg/YRS2wtH4uB
      discord:        https://discord.gg/YRS2wtH4uB

    jane:
      name:           Jane
      site:           https://ai.supremacy.sg
      avatar:         assets/images/jane.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          info@supremacy.sg
      twitter:        https://discord.gg/YRS2wtH4uB
      discord:        https://discord.gg/YRS2wtH4uB
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Jane
      avatar: assets/images/jane.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]